-- MySQL Script generated by MySQL Workbench
-- Mon May 30 14:01:45 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema diplom
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema diplom
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `diplom` DEFAULT CHARACTER SET utf8 ;
USE `diplom` ;

-- -----------------------------------------------------
-- Table `diplom`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diplom`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diplom`.`cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diplom`.`cities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diplom`.`landmarks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diplom`.`landmarks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NULL,
  `description` VARCHAR(2000) NULL,
  `picture` VARCHAR(100) NULL,
  `category_id` INT NOT NULL,
  `city_id` INT NOT NULL,
  `map` VARCHAR(1000) NOT NULL,
  `visiting_time` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_landmarks_categories_idx` (`category_id` ASC) VISIBLE,
  INDEX `fk_landmarks_cities1_idx` (`city_id` ASC) VISIBLE,
  CONSTRAINT `fk_landmarks_categories`
    FOREIGN KEY (`category_id`)
    REFERENCES `diplom`.`categories` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_landmarks_cities1`
    FOREIGN KEY (`city_id`)
    REFERENCES `diplom`.`cities` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diplom`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diplom`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `fullname` VARCHAR(50) NULL,
  `birth_date` DATE NULL,
  `role` VARCHAR(45) NOT NULL,
  `city` VARCHAR(60) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diplom`.`landmarks_in_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diplom`.`landmarks_in_list` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rating` INT NULL,
  `visit_date` DATE NOT NULL,
  `user_id` INT NOT NULL,
  `landmark_id` INT NOT NULL,
  INDEX `fk_landmarks_list_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_landmarks_list_landmarks1_idx` (`landmark_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_landmarks_list_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `diplom`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_landmarks_list_landmarks1`
    FOREIGN KEY (`landmark_id`)
    REFERENCES `diplom`.`landmarks` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diplom`.`pictures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diplom`.`pictures` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `file_name` VARCHAR(100) NOT NULL,
  `landmark_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pictures_landmarks1_idx` (`landmark_id` ASC) VISIBLE,
  CONSTRAINT `fk_pictures_landmarks1`
    FOREIGN KEY (`landmark_id`)
    REFERENCES `diplom`.`landmarks` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
