// fetch
export const FETCH_LANDMARKS_START = "FETCH_LANDMARKS_START";
export const FETCH_LANDMARKS_SUCCESS = "FETCH_LANDMARKS_SUCCESS";
export const FETCH_LANDMARKS_FAIL = "FETCH_LANDMARKS_FAIL";

export const FETCH_LANDMARK_START = "FETCH_LANDMARK_START";
export const FETCH_LANDMARK_SUCCESS = "FETCH_LANDMARK_SUCCESS";
export const FETCH_LANDMARK_FAIL = "FETCH_LANDMARK_FAIL";

export const FETCH_USER_START = "FETCH_USER_START";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAIL = "FETCH_USER_FAIL";

export const FETCH_CITY_START = "FETCH_CITY_START";
export const FETCH_CITY_SUCCESS = "FETCH_CITY_SUCCESS";
export const FETCH_CITY_FAIL = "FETCH_CITY_FAIL";

export const FETCH_CATEGORY_START = "FETCH_CATEGORY_START";
export const FETCH_CATEGORY_SUCCESS = "FETCH_CATEGORY_SUCCESS";
export const FETCH_CATEGORY_FAIL = "FETCH_CATEGORY_FAIL";
// get by id
export const GET_LANDMARK_START = "GET_LANDMARK_START";
export const GET_LANDMARK_SUCCESS = "GET_LANDMARK_SUCCESS";
export const GET_LANDMARK_FAIL = "GET_LANDMARK_FAIL";
// create
export const CREATE_LANDMARK_START = "CREATE_LANDMARK_START";
export const CREATE_LANDMARK_SUCCESS = "CREATE_LANDMARK_SUCCESS";
export const CREATE_LANDMARK_FAIL = "CREATE_LANDMARK_FAIL";
// delete
export const DELETE_LANDMARKS_START = "DELETE_LANDMARKS_START";
export const DELETE_LANDMARKS_SUCCESS = "DELETE_LANDMARKS_SUCCESS";
export const DELETE_LANDMARKS_FAIL = "DELETE_LANDMARKS_FAIL";
// update
export const UPDATE_LANDMARK_START = "UPDATE_LANDMARK_START";
export const UPDATE_LANDMARK_SUCCESS = "UPDATE_LANDMARK_SUCCESS";
export const UPDATE_LANDMARK_FAIL = "UPDATE_LANDMARK_FAIL";

// fetch
export const FETCH_USERS_START = "FETCH_USERS_START";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAIL = "FETCH_USERS_FAIL";
// get by id
export const GET_USER_START = "GET_USER_START";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL";
// create
export const CREATE_USER_START = "CREATE_USER_START";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAIL = "CREATE_USER_FAIL";
// delete
export const DELETE_USERS_START = "DELETE_USERS_START";
export const DELETE_USERS_SUCCESS = "DELETE_USERS_SUCCESS";
export const DELETE_USERS_FAIL = "DELETE_USERS_FAIL";
// update
export const UPDATE_USER_START = "UPDATE_USER_START";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";

export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const CLEAR_CURRENT_USER = "CLEAR_CURRENT_USER";

export const FETCH_LANDMARKS_USER_START = "FETCH_LANDMARKS_USER_START";
export const FETCH_LANDMARKS_USER_SUCCESS = "FETCH_LANDMARKS_USER_SUCCESS";
export const FETCH_LANDMARKS_USER_FAIL = "FETCH_LANDMARKS_USER_FAIL";

export const CREATE_LANDMARKS_USER_START = "CREATE_LANDMARKS_USER_START";
export const CREATE_LANDMARKS_USER_SUCCESS = "CREATE_LANDMARKS_USER_SUCCESS";
export const CREATE_LANDMARKS_USER_FAIL = "CREATE_LANDMARKS_USER_FAIL";
